export type ViewMode = 'home' | 'panel' | 'node';

export type AuthType = 'password' | 'privateKey';

export type SystemType = 'debian-ubuntu' | 'centos' | 'autodetect';

export type ScriptType = 'recommended' | 'official' | 'custom';

export type ProtocolType = 'VLESS' | 'VMess' | 'Trojan' | 'Shadowsocks';

export type TransportType = 'TCP' | 'WebSocket' | 'gRPC' | 'mKCP';

export type SecurityType = 'None' | 'TLS' | 'Reality';

export interface PanelDeployForm {
  ipOrDomain: string;
  sshPort: number;
  sshUser: string;
  authType: AuthType;
  sshPassword?: string;
  sshPrivateKey?: string;
  sshPrivateKeyPassphrase?: string;
  panelPort?: string;
  panelPath?: string;
  domain?: string;
  systemType: SystemType;
  autoSSL: boolean;
  scriptType?: ScriptType;
  customScriptUrl?: string;
}

export interface PanelResult {
  id: string;
  createdAt: string;
  accessUrl: string;
  protocol: 'https' | 'http';
  host: string;
  port: string;
  path: string;
  username: string;
  password?: string;
  apiToken?: string;
  sslEnabled: boolean;
  installCommand: string;
  scriptType?: string;
  scriptUrl?: string;
}

export interface SocksItem {
  id: string;
  raw: string;
  address: string;
  port: number;
  user?: string;
  pass?: string;
  valid: boolean;
  tag: string;
}

export interface NodeDeployForm {
  // Panel details
  panelAddress: string;
  panelPort: string;
  panelPath: string;
  panelProtocol: 'http' | 'https';
  allowInsecureTls: boolean;
  panelUser: string;
  panelPass: string;
  panelToken?: string;

  // Node protocol details
  nodeName: string;
  protocol: ProtocolType;
  transport: TransportType;
  security: SecurityType;
  inboundPort?: string;
  sni?: string;
  shortId?: string; // For Reality
  pathOrServiceName?: string;
  encryption?: string; // For VMess / Shadowsocks
  
  // Limits
  trafficLimitGb?: number;
  expireDays?: number;

  // SOCKS Chain
  socksRawInput: string;
  autoOutbound: boolean;
  autoRouting: boolean;
  enableLoadBalance: boolean;
}

export interface NodeResult {
  id: string;
  createdAt: string;
  nodeName: string;
  protocol: ProtocolType;
  transport: TransportType;
  security: SecurityType;
  shareLink: string;
  subscriptionUrl?: string;
  inboundId: number;
  inboundTag: string;
  inboundPort: number;
  uuid: string;
  socksConfigured: boolean;
  socksList: SocksItem[];
  xrayOutboundsJson: string;
  xrayRoutingJson: string;
  socksExplanation: string;
  realityParamsUsed?: {
    sni: string;
    publicKey: string;
    shortId: string;
    autoGenerated: boolean;
  } | null;
}

export interface ToastMessage {
  id: string;
  type: 'success' | 'error' | 'info' | 'warning';
  title: string;
  message?: string;
}

export interface HistoryItem {
  id: string;
  timestamp: string;
  type: 'panel' | 'node';
  title: string;
  summary: string;
  panelData?: PanelResult;
  nodeData?: NodeResult;
}
